#include "ascii_host_types.h"

namespace pae::protocol_lab_ui {

std::string_view AsciiCodecStatusName(CodecStatus status) noexcept {
#define PAE_ASCII_CODEC_CASE(name) case CodecStatus::name: return #name
  switch (status) {
    PAE_ASCII_CODEC_CASE(OK); PAE_ASCII_CODEC_CASE(INVALID_ARGUMENT);
    PAE_ASCII_CODEC_CASE(INVALID_COMPILED_PROTOCOL);
    PAE_ASCII_CODEC_CASE(RESOURCE_LIMIT_EXCEEDED); PAE_ASCII_CODEC_CASE(ALLOCATION_FAILED);
    PAE_ASCII_CODEC_CASE(WORKSPACE_BUSY); PAE_ASCII_CODEC_CASE(INPUT_VALUES_TOO_MANY);
    PAE_ASCII_CODEC_CASE(UNKNOWN_MESSAGE); PAE_ASCII_CODEC_CASE(AMBIGUOUS_MESSAGE);
    PAE_ASCII_CODEC_CASE(OUTPUT_SLOTS_TOO_SMALL); PAE_ASCII_CODEC_CASE(INTEGRITY_FAILED);
    PAE_ASCII_CODEC_CASE(MESSAGE_NOT_ALLOWED); PAE_ASCII_CODEC_CASE(FIELD_REFERENCE_MISMATCH);
    PAE_ASCII_CODEC_CASE(DUPLICATE_FIELD); PAE_ASCII_CODEC_CASE(MISSING_FIELD);
    PAE_ASCII_CODEC_CASE(TYPE_MISMATCH); PAE_ASCII_CODEC_CASE(VALUE_NOT_REPRESENTABLE);
    PAE_ASCII_CODEC_CASE(BYTES_LENGTH_MISMATCH); PAE_ASCII_CODEC_CASE(UNKNOWN_ENUM_VALUE);
    PAE_ASCII_CODEC_CASE(ENUM_REFERENCE_MISMATCH); PAE_ASCII_CODEC_CASE(CONSTANT_FIELD_OVERRIDE);
    PAE_ASCII_CODEC_CASE(INPUT_OUTPUT_OVERLAP); PAE_ASCII_CODEC_CASE(BUFFER_TOO_SMALL);
    PAE_ASCII_CODEC_CASE(FINAL_REVIEW_FAILED); PAE_ASCII_CODEC_CASE(ASCII_CHARACTER_NOT_ALLOWED);
    PAE_ASCII_CODEC_CASE(ASCII_TERMINATOR_CONFLICT); PAE_ASCII_CODEC_CASE(OPERATION_NOT_SUPPORTED);
    PAE_ASCII_CODEC_CASE(COMPUTED_FIELD_OVERRIDE); PAE_ASCII_CODEC_CASE(LENGTH_MISMATCH);
    PAE_ASCII_CODEC_CASE(INTERNAL_ERROR);
  }
#undef PAE_ASCII_CODEC_CASE
  return "UNKNOWN_CODEC_STATUS";
}

}  // namespace pae::protocol_lab_ui
