set(expected "$<$<AND:$<COMPILE_LANG_AND_ID:CXX,MSVC>,$<NOT:$<BOOL:$<TARGET_PROPERTY:PAE_MSVC_SOURCE_CHARSET_SUPPLIED>>>>:/source-charset:utf-8>")
file(READ "${OPTIONS_FILE}" actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Public compile options changed or internal options leaked: ${actual}")
endif()
foreach(configuration IN ITEMS Debug Release)
    file(READ "${SDK_CONFIG_ROOT}/${configuration}/PAEConfig.cmake" config)
    string(FIND "${config}" "\"${expected}\"" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Installed ${configuration} target is missing the source charset")
    endif()
    foreach(forbidden IN ITEMS "/W4" "/permissive-" "/utf-8" "/Zc:__cplusplus" "pae::project_options")
        string(FIND "${config}" "${forbidden}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "Installed target leaks ${forbidden}")
        endif()
    endforeach()
endforeach()
if(DEFINED EVALUATED_ROOT AND NOT EVALUATED_ROOT STREQUAL "")
    file(READ "${EVALUATED_ROOT}/${CONFIGURATION}/CXX/default.txt" default)
    file(READ "${EVALUATED_ROOT}/${CONFIGURATION}/CXX/host.txt" host)
    file(READ "${EVALUATED_ROOT}/${CONFIGURATION}/CXX/project.txt" project)
    file(READ "${EVALUATED_ROOT}/${CONFIGURATION}/CXX/execution936.txt" execution936)
    if(NOT default STREQUAL "/source-charset:utf-8" OR NOT host STREQUAL "/utf-8" OR
       NOT execution936 STREQUAL "/execution-charset:.936;/source-charset:utf-8")
        message(FATAL_ERROR "Unexpected evaluated consumer options: ${default} | ${host} | ${execution936}")
    endif()
    # Duplicate identical source options are deduplicated by CMake at compiler invocation.
    set(expected_project /W4 /permissive- /Zc:__cplusplus /source-charset:utf-8 /execution-charset:utf-8)
    list(REMOVE_DUPLICATES project)
    list(SORT project)
    list(SORT expected_project)
    if(NOT project STREQUAL expected_project)
        message(FATAL_ERROR "Repository UTF-8 options changed: ${project}")
    endif()
endif()
message(STATUS "Default source charset, explicit host opt-out, and repository encoding verified")
