cmake_minimum_required(VERSION 3.25)
foreach(variable IN ITEMS PAE_UI_EXE PAE_LIBRARY_KIND PAE_QT_ROOT PAE_BUILD_CONFIG PAE_DEPLOY_DIR PAE_ALLOWED_OUT_ROOT PAE_CONFIG_FILES)
  if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
    message(FATAL_ERROR "DeployPaeLabRun requires ${variable}")
  endif()
endforeach()
if(NOT PAE_LIBRARY_KIND STREQUAL "STATIC" AND NOT PAE_LIBRARY_KIND STREQUAL "SHARED")
  message(FATAL_ERROR "Unsupported PAE library kind: ${PAE_LIBRARY_KIND}")
endif()
if(PAE_LIBRARY_KIND STREQUAL "SHARED")
  foreach(variable IN ITEMS PAE_RUNTIME_DLL PAE_RUNTIME_SHA256)
    if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
      message(FATAL_ERROR "Shared Lab deployment requires ${variable}")
    endif()
  endforeach()
  if(NOT EXISTS "${PAE_RUNTIME_DLL}")
    message(FATAL_ERROR "Missing PAE shared runtime: ${PAE_RUNTIME_DLL}")
  endif()
  file(SHA256 "${PAE_RUNTIME_DLL}" actual_pae_runtime_sha256)
  string(TOLOWER "${actual_pae_runtime_sha256}" actual_pae_runtime_sha256)
  string(TOLOWER "${PAE_RUNTIME_SHA256}" expected_pae_runtime_sha256)
  if(NOT actual_pae_runtime_sha256 STREQUAL expected_pae_runtime_sha256)
    message(FATAL_ERROR "PAE shared runtime hash changed before deployment")
  endif()
endif()
cmake_path(NORMAL_PATH PAE_DEPLOY_DIR OUTPUT_VARIABLE deploy_dir)
cmake_path(NORMAL_PATH PAE_ALLOWED_OUT_ROOT OUTPUT_VARIABLE allowed_root)
cmake_path(IS_PREFIX allowed_root "${deploy_dir}" NORMALIZE bounded)
if(NOT bounded OR deploy_dir STREQUAL allowed_root)
  message(FATAL_ERROR "Refusing unbounded Lab deployment: ${deploy_dir}")
endif()
if(EXISTS "${deploy_dir}")
  file(GLOB existing LIST_DIRECTORIES true "${deploy_dir}/*")
  if(existing)
    message(FATAL_ERROR "Refusing to overwrite non-empty deployment directory: ${deploy_dir}")
  endif()
endif()
if(NOT PAE_BUILD_CONFIG STREQUAL "Debug" AND NOT PAE_BUILD_CONFIG STREQUAL "Release")
  message(FATAL_ERROR "Standalone deployment supports only Debug and Release")
endif()
if(PAE_BUILD_CONFIG STREQUAL "Debug")
  set(qt_dir debug)
  set(suffix d)
else()
  set(qt_dir release)
  set(suffix "")
endif()
set(runtime_files
  "${PAE_QT_ROOT}/bin/${qt_dir}/Qt5Core${suffix}.dll"
  "${PAE_QT_ROOT}/bin/${qt_dir}/Qt5Gui${suffix}.dll"
  "${PAE_QT_ROOT}/bin/${qt_dir}/Qt5Widgets${suffix}.dll")
set(platform "${PAE_QT_ROOT}/bin/${qt_dir}/platforms/qwindows${suffix}.dll")
foreach(file IN LISTS runtime_files)
  if(NOT EXISTS "${file}")
    message(FATAL_ERROR "Missing Qt runtime: ${file}")
  endif()
endforeach()
if(NOT EXISTS "${platform}" OR NOT EXISTS "${PAE_UI_EXE}")
  message(FATAL_ERROR "Missing Lab executable or Qt platform plugin")
endif()
file(MAKE_DIRECTORY "${deploy_dir}/platforms" "${deploy_dir}/configs")
file(COPY_FILE "${PAE_UI_EXE}" "${deploy_dir}/pae_protocol_lab_ui.exe" ONLY_IF_DIFFERENT)
if(PAE_LIBRARY_KIND STREQUAL "SHARED")
  file(COPY_FILE "${PAE_RUNTIME_DLL}" "${deploy_dir}/pae.dll" ONLY_IF_DIFFERENT)
  file(SHA256 "${deploy_dir}/pae.dll" deployed_pae_runtime_sha256)
  string(TOLOWER "${deployed_pae_runtime_sha256}" deployed_pae_runtime_sha256)
  if(NOT deployed_pae_runtime_sha256 STREQUAL expected_pae_runtime_sha256)
    message(FATAL_ERROR "Deployed PAE shared runtime hash mismatch")
  endif()
endif()
foreach(file IN LISTS runtime_files)
  cmake_path(GET file FILENAME name)
  file(COPY_FILE "${file}" "${deploy_dir}/${name}" ONLY_IF_DIFFERENT)
endforeach()
file(COPY_FILE "${platform}" "${deploy_dir}/platforms/qwindows${suffix}.dll" ONLY_IF_DIFFERENT)
string(REPLACE "|" ";" configs "${PAE_CONFIG_FILES}")
foreach(file IN LISTS configs)
  if(NOT EXISTS "${file}" OR NOT "${file}" MATCHES "\\.pae\\.json$")
    message(FATAL_ERROR "Invalid Lab config input: ${file}")
  endif()
  cmake_path(GET file FILENAME name)
  file(COPY_FILE "${file}" "${deploy_dir}/configs/${name}" ONLY_IF_DIFFERENT)
endforeach()
