if(NOT DEFINED PAE_SOURCE OR NOT DEFINED PAE_GATE_BINARY)
    message(FATAL_ERROR "Pass PAE_SOURCE and PAE_GATE_BINARY outside source files.")
endif()
foreach(case IN ITEMS default missing_all missing_v11)
    set(options -DPAE_BUILD_TESTING=OFF -DBUILD_TESTING=OFF)
    if(NOT case STREQUAL "default")
        list(APPEND options -DPAE_BUILD_HOST_ENDPOINT_SLICE=ON)
    endif()
    if(case STREQUAL "missing_v11")
        list(APPEND options -DPAE_BUILD_LOADER_SCHEMA_IR_SLICE=ON
            -DPAE_BUILD_COMPLETE_RECORD_CODEC_SLICE=ON -DPAE_BUILD_STREAM_FRAMING_SLICE=ON
            -DPAE_ENABLE_SCHEMA_V11_ASCII_STREAM_FRAMING=OFF)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${PAE_SOURCE}"
        -B "${PAE_GATE_BINARY}/${case}" -G "Visual Studio 18 2026" -A x64 ${options}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    file(WRITE "${PAE_GATE_BINARY}/${case}.log" "${output}\n${error}")
    if(case STREQUAL "default")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Default configure failed: ${error}")
        endif()
        file(READ "${PAE_GATE_BINARY}/${case}/CMakeCache.txt" cache)
        if(NOT cache MATCHES "PAE_BUILD_HOST_ENDPOINT_SLICE:BOOL=OFF")
            message(FATAL_ERROR "Host slice not default OFF")
        endif()
        if(EXISTS "${PAE_GATE_BINARY}/${case}/src/host_endpoint/pae_host_endpoint.vcxproj")
            message(FATAL_ERROR "Default build unexpectedly contains host target")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "Host endpoint slice requires explicit Loader")
        message(FATAL_ERROR "${case} did not reject at the precise host gate: ${error}")
    endif()
    message(STATUS "host gate ${case}: PASS")
endforeach()
